[build]
builder = "NIXPACKS"

[[services]]
name = "dashboard"
source = "dashboard"

[services.build]
buildCommand = "npm install && npm run build"
startCommand = "npm start"

[[services]]
name = "bot"
source = "bot"

[services.build]
buildCommand = "pip install -r requirements.txt"
startCommand = "python main.py"
